version: '3'
services:
  auth_service:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/configs:/etc/nginx/conf.d:z
    depends_on:
      - auth_service
    ports:
      - 80:80
